EVG-18225: Check status code and report error while getting signed ur…
evergreen-ci/poplar pull request #116
Opened 2022-11-11 14:32 UTC by mridul-augustine

…l in poplar

2022-11-11 23:32 UTC, julianedwards requested changes

2022-11-11 23:32 UTC, julianedwards commented on rpc/client.go
> +		return "", errors.Errorf("Non-OK HTTP status. Status Code: %d. Status Text: %s", response.StatusCode, http.StatusText(response.StatusCode))
Can you change this to `"failed to get the Data-Pipes signed URL with response '%s'", response.Status`.

2022-11-11 23:32 UTC, julianedwards commented on rpc/client.go
> +		"Status Code": response.StatusCode,
I would add more context to this message.

2022-11-11 23:32 UTC, julianedwards commented on rpc/client.go
> +		return errors.Errorf("Non-OK HTTP status. Status Code: %d. Status Text: %s", response.StatusCode, http.StatusText(response.StatusCode))
Can you change this to `"failed to upload test report to the Data-Pipes service with response '%s'", response.Status`.

2022-11-11 23:32 UTC, julianedwards commented on rpc/client.go
>  		return "", err
I would wrap this error.

2022-11-11 23:32 UTC, julianedwards commented on rpc/client.go
>  	body, error := ioutil.ReadAll(response.Body)
`err`

2022-11-11 23:32 UTC, julianedwards commented on rpc/client.go
>  		return "", err
Also, on L214 we aren't properly checking the error, you can change it to:
```
if err = json.Unmarshal(body, &responseBody); err != nil {
        return "", errors.Wrap(err, "parsing signed URL response")
}
```

2022-11-11 23:32 UTC, julianedwards commented on rpc/client.go
>  	if error != nil {
`if err`

2022-11-14 19:29 UTC, julianedwards requested changes
I think all of the debug logs are a bit overkill, but if you find them useful feel free to keep them.

2022-11-14 20:23 UTC, mridul-augustine commented
> I think all of the debug logs are a bit overkill, but if you find them useful feel free to keep them.

I just added one debug :) others were just the old ones. Just added more context

2022-11-15 16:13 UTC, julianedwards requested changes
A few more things!

2022-11-21 21:05 UTC, julianedwards approved these changes

2022-11-21 21:07 UTC, merged